### ISSUE TITLE
implementation?

### ISSUE THREAD

**Issue by Dontmindmes** [Leeon123/golang-httpflood#1]
Hey so im making  probebly the first IRC botnet in golang

https://github.com/Dontmindmes/Go-IRC-Botnet
and was woundering if you would like to help me implement more features such as actuall ddos

**Comment by Leeon123** [comment]
sure, i'm finding a way to build a p2p botnet with golang. Now is the way :)

**Comment by Dontmindmes** [comment]
Alrighty :) I just managed to implement your flood in to it, I'll upload the code when I'm home!

**Comment by Leeon123** [comment]
Now i have a problem, how could we run the client background?I havs done the ddos modules(dns query flood,httpflood),but i can't run it in background(i don't know why it will not get into irc-server ),And i have a suggestion is try to not use the randstring() because it will be the same on other  Machine.

**Comment by Leeon123** [comment]
My ambition is not only x86 and x86_64 windows . Such as ppc, arm ,mips are more suitable for iot botnet.

**Comment by Dontmindmes** [comment]
By running in the background you mean running with out any GUI or Console is that correct? If so I'm pretty sure golang has a build option to disable all GUI features

I'll change Rand right now, thanks for pointing that out

And yes since golang is ment for cross development it will be easy getting it to run on other OS, Linux, Mac I will update the code in a bit

**Comment by Dontmindmes** [comment]
Yes i was able to make a build that runs in back ground! do you have discord?

**Comment by Leeon123** [comment]
Yes i have : Leeon123#5277

**Comment by Dontmindmes** [comment]
Great i have sent you friend request on discord, send me amessage when you add me back
