### ISSUE TITLE
run script

### ISSUE THREAD

**Issue by swdlo9** [Leeon123/golang-httpflood#10]
Hi i use this comand to run the script, ./httpflood www.example.com 80 400 post 100 header.txt
but the script doesn't start

and show me this.
Post Mode will use header.txt as data
If you are using linux please run 'ulimit -n 999999' first!!!
Usage:  ./httpflood <ip> <port> <threads> <page> <get/post> <seconds> <header.txt/nil>

how i can start the script?

**Comment by Leeon123** [comment]
Did you write down the custom header in header.txt ? Else just use nil as it, please see the readme.md clearly.

**Comment by sedklo** [comment]
this comand not ru the script ./httpflood www.example.com 80 400 post 100 header.txt

I have tried this command and it does not work either

./httpflood www.example.com 80 400 post 100 header.txt/nil

I want to know, what is the command to start the script? Can you tell me please? I am using ubuntu 18.10

**Comment by sedklo** [comment]
in the <page> section what do I have to put?

**Comment by sedklo** [comment]
page section

**Comment by Leeon123** [comment]
./httpflood www.example.com 80 400 get / 100 nil
