### ISSUE TITLE
script

### ISSUE THREAD

**Issue by sedklo** [Leeon123/golang-httpflood#11]
the script works fine but when you launch the attack on a web page in a few seconds i have this message
Connection Down !!!
Connection Down !!!
Connection Down !!!
Connection Down !!!
Connection Down !!!
Connection Down !!!
Connection Down !!!
Connection Down !!!
this happens in all the web pages that I have tried
Why is this happening?

**Comment by Leeon123** [comment]
The remote server closed your connection
