### ISSUE TITLE
Upgrade script

### ISSUE THREAD

**Issue by andress134** [Leeon123/golang-httpflood#14]
Hello sir @Leeon123 i sugest to upgrade your script using this lib https://github.com/galmi/grucaptcha or https://github.com/Wyvern-Balls/Cloudflare-Bypass-Script  for bypass iuam and hcaptcha, also your script can't send attack to url using https:// can u solve i?

**Comment by Leeon123** [comment]
I'll check it out, and use port 443 can enable ssl connection so you can attack https://.
