### ISSUE TITLE
proxy support ?

### ISSUE THREAD

**Issue by webr00t** [Leeon123/golang-httpflood#15]
Hi.

You have created a very fast and powerful script. thank you so much.

but you have to do the proxy support version.

**Comment by webr00t** [comment]
can you help me ? @Leeon123

**Comment by Leeon123** [comment]
Nah, I have no plan to release it.

**Comment by Scanyalx** [comment]
Has anyone been able to run it with its proxy?

**Comment by jimmyduang** [comment]
hi,i implement the proxy socks5 in here ,[click me](https://github.com/jimmyduang/golang-httpflood)
