### ISSUE TITLE
Has anyone been able to run it with its proxy?

### ISSUE THREAD

**Issue by Scanyalx** [Leeon123/golang-httpflood#18]
Has anyone been able to run it with its proxy?

**Comment by Leeon123** [comment]
I did but why don't write it by yourself.

**Comment by jimmyduang** [comment]
hi,i implement the proxy socks5 in here ,[click me](https://github.com/jimmyduang/golang-httpflood)

**Comment by jimmyduang** [comment]
@Scanyalx
