### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by kxngarooPHP** [Leeon123/golang-httpflood#2]
even when a site isnt down, it says "Connection Down!!!". and even if the site goes down i would like to keep hitting. how do i fix??

**Comment by Leeon123** [comment]
When the site isn't down and it said "connection down" mean the site do something to protect itself. Maybe you should try port 80 on https server.

**Comment by Leeon123** [comment]
If the site got down it will continue hit except the site connection full or "fully" down not like connection timeout and reset.
