### ISSUE TITLE
Issue while running in windows GO Lang.

### ISSUE THREAD

**Issue by abhithenua** [Leeon123/golang-httpflood#4]
When I run command 
go run httpflood.go 
it says
# command-line-arguments
.\httpflood.go:214:69: constant 1000000000000000000 overflows int

Any solutions?

And I want to talk to you about CC attacker too, please check your gmail and really you are brilliant guy.

**Comment by Leeon123** [comment]
That mybe your problem. I ran it normally. Please tell me the version of your Golang.

**Comment by abhithenua** [comment]
> That mybe your problem. I ran it normally. Please tell me the version of your Golang.

go version go1.13.3 windows/386 

It's the version and i'm running it on windows.

**Comment by Leeon123** [comment]
Use amd64 bro...that will fix it.

**Comment by Leeon123** [comment]
@abhithenua Now it updated for 386 systems and the base of socks5 is coming.
