### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by OhMySynaticall** [Leeon123/golang-httpflood#8]
go build httpflood.go does not work

**Comment by Leeon123** [comment]
Put ur screenshot here

**Comment by Sauug** [comment]
install go correctly :) 

https://golang.org/dl/
tar -xzf <gofile>
mv go /usr/local/go
cd /usr/local
chown root:root /usr/local/go
chmod 755 go
cd
mkdir golang
nano /etc/profile
export PATH=$PATH:/usr/local/go/bin => SAVE (**ctrl** + **x**, **y** and **enter**)
export GOPATH=$HOME/golang
export PATH=$HOME/golang/bin:$PATH ==> SAVE
sudo chmod -R 777 ~/gocode
Reboot and retest go build httpflood.go
