### ISSUE TITLE
golang

### ISSUE THREAD

**Issue by sedklo** [Leeon123/golang-httpflood#9]
Hi when I put go build httpflood.go I get this error
# command-line-arguments
./httpflood.go:209:5: syntax error: unexpected else at end of statement
./httpflood.go:212:3: syntax error: non-declaration statement outside function body
and I have golang installed in my vps, how can I solve this problem?
Another question, I am seeing on YouTube that there is a script for bypass cloudflare UAM and CAPTCHA, please if you have that script can you share it? Thank you

**Comment by Leeon123** [comment]
the issue is fixed and bypassing uam or captcha, you need a js resolver or resolver api.
